

export const usernames = [
    'Park Jongho',
    'Stephen Park',
    'BG Kim',
    'Adam Smith',
    'Tony',
    'Hanseul',
    'Marie',
    'Cyndy Kim',
    'Kei Ibaraki',
    'Joker',
    'Joker2',
    'Thral',
    'Piero',
    'Coffee',
    'DarkKnight',
    'Jun',
    'Jenny',
    'JoJunghyung',
    'Ice Breaker',
    'Z Bar',
    'Bag Packer',
    'ILikeCleanWater'
];

export const hashtags = [
    'BlackLivesMetter',
    'BLM',
    'WhatIsJustice',
    'HumanLivesMetter',
    'BetterThanYesterday',
    'WIJ',
    'ThePowerOfDog',
    'ABirdWhoDrinksTears',
    'IMissedTheSign',
    'YouDontHaveToWorryBaby',
    'WaitingForMe',
    'HomeSweetHome',
    'WalkingDown',
    'AmericanIdiot',
    '2002',
    'YouLookHappierYouDo',
    'IDoIDo',
    'ABC',
    'AAA',
    'BBB',
    'CCCCCC',
    'ASDFASF',
    '1238djna'
];


export const communities = [
    'ARMY',
    'WOW',
    'Baseball',
    'LeagueOfLegends',
    'LOL',
    'SeoTaiji',
    'Rock',
    'ClassicMusic',
    'LedZeppline',
    'GreenDay',
    'GunsNRoses',
    'Programming',
    'Coffee',
    'Animals',
    'Apes',
    'Jenny',
    'Mogao',
    'BlackLivesMetter',
];